#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# GistID: 2957960

# {{{ Prezto settings:
#
# Modules: editor, history, completion, utility, prompt, fasd, git, history-substring-search
# Editor keymap: vi
# Theme: bpm (https://gist.github.com/4230860)
#
# }}}

#}}}

#{{{ Completion

# Fall back to file completion if all else fails
orig_comp="$(zstyle -L ':completion:\*' completer 2>> "/dev/null")"
fasd_comp="_fasd_zsh_word_complete_trigger"
if [ "$orig_comp" ]; then
  case $orig_comp in
    # make sure the fasd completor goes after _files
    *_files*$fasd_comp*);;
    *$fasd_comp*) eval "${${orig_comp}/${fasd_comp}/_files} ${fasd_comp}";;
    *) eval "$orig_comp _files";;
  esac
else
  zstyle ':completion:*' completer _expand _complete _match _approximate _files _correct
fi
unset orig_comp fasd_comp

# Files to ignore during completion
fignore=(DS_Store $fignore)

# <C-F> for file completion
zle -C complete-file menu-expand-or-complete _generic
zstyle ':completion:complete-file:*' completer _files
bindkey -M viins '^F'      complete-file

#}}}

#{{{ Extra Vim Key binding

# Movement
bindkey -M viins '^E'   end-of-line
bindkey -M viins '^A'   vi-beginning-of-line
bindkey -M vicmd '^E'   end-of-line
bindkey -M vicmd '^A'   vi-beginning-of-line
bindkey "\e[1;5C"       forward-word            # Ctrl + right arrow
bindkey "\e[1;5D"       backward-word           # Ctrl + left arrow

# Kill line
bindkey -M viins '^K'   kill-line
bindkey -M viins '^U'   backward-kill-line
bindkey -M vicmd '^K'   kill-line
bindkey -M vicmd '^U'   backward-kill-line

# History
# Search based on what you typed in already
bindkey -M vicmd "//"   history-beginning-search-forward
bindkey -M vicmd "??"   history-beginning-search-backward

# Backspace
bindkey -M viins '^W'   backward-kill-word

# Unbind <C-[>
bindkey '^['            self-insert

#}}}

#{{{ Functions

function nametab {
  echo -ne "\033]0;"$@"\007"
}

#}}}

#{{{ Options

setopt AUTO_CD

setopt CORRECT

#}}}
